# Generated by Django 5.0.4 on 2024-09-30 22:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_personajes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_producto', models.TextField(max_length=50)),
                ('desc_producto', ckeditor.fields.RichTextField(null=True)),
                ('precio_producto', models.IntegerField()),
                ('precioreb_producto', models.IntegerField(null=True)),
                ('stock_producto', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Personajes',
        ),
    ]
