<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-12-02 23:19
=======
# Generated by Django 5.1.2 on 2024-12-03 05:43
>>>>>>> bf6c5d2bc7b448688cd43b40452a13468949292f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_comprar_detallecompra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito_detalle',
            unique_together={('carrito_det', 'producto')},
        ),
    ]
