# Generated by Django 5.0.6 on 2024-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_productos_delete_personajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_producto',
            field=models.ImageField(default='', upload_to='productos'),
        ),
    ]
